### ISSUE TITLE
Soft crash on input to search bar

### ISSUE THREAD

**Issue by jakubdabek** [jplatte/caniuse.rs#52]
As soon as I try to enter anything in the search bar I get the output in console:

```rust
caniuse_rs.js:458 panicked at 'No current Scope. `use_context` can only be called inside function components', /home/jplatte/.cargo/registry/src/github.com-1ecc6299db9ec823/yew-0.19.3/src/functional/hooks/use_context.rs:38:10

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (https://caniuse.rs/caniuse_rs.js:446:23)
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[760]:0x547e2
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[310]:0x39f61
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[604]:0x42e91
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[718]:0x43feb
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[98]:0x16538
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[204]:0x2d94c
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[93]:0x13d8e
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[277]:0x37f2e
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[387]:0x3dca6


imports.wbg.__wbg_error_09919627ac0992f5 @ caniuse_rs.js:458
$func760 @ caniuse_rs.wasm:0x54867
$func310 @ caniuse_rs.wasm:0x39f61
$func604 @ caniuse_rs.wasm:0x42e91
$func718 @ caniuse_rs.wasm:0x43feb
$func98 @ caniuse_rs.wasm:0x16538
$func204 @ caniuse_rs.wasm:0x2d94c
$func93 @ caniuse_rs.wasm:0x13d8e
$func277 @ caniuse_rs.wasm:0x37f2e
$func387 @ caniuse_rs.wasm:0x3dca6
$func363 @ caniuse_rs.wasm:0x3cda0
$func104 @ caniuse_rs.wasm:0x1937f
$func715 @ caniuse_rs.wasm:0x43f0e
$_dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hffc6db5e0694434e @ caniuse_rs.wasm:0x43b46
__wbg_adapter_26 @ caniuse_rs.js:257
real @ caniuse_rs.js:243
caniuse_rs.wasm:0x39f84 Uncaught RuntimeError: unreachable
    at caniuse_rs.wasm:0x39f84
    at caniuse_rs.wasm:0x42e91
    at caniuse_rs.wasm:0x43feb
    at caniuse_rs.wasm:0x16538
    at caniuse_rs.wasm:0x2d94c
    at caniuse_rs.wasm:0x13d8e
    at caniuse_rs.wasm:0x37f2e
    at caniuse_rs.wasm:0x3dca6
    at caniuse_rs.wasm:0x3cda0
    at caniuse_rs.wasm:0x1937f
$func310 @ caniuse_rs.wasm:0x39f84
$func604 @ caniuse_rs.wasm:0x42e91
$func718 @ caniuse_rs.wasm:0x43feb
$func98 @ caniuse_rs.wasm:0x16538
$func204 @ caniuse_rs.wasm:0x2d94c
$func93 @ caniuse_rs.wasm:0x13d8e
$func277 @ caniuse_rs.wasm:0x37f2e
$func387 @ caniuse_rs.wasm:0x3dca6
$func363 @ caniuse_rs.wasm:0x3cda0
$func104 @ caniuse_rs.wasm:0x1937f
$func715 @ caniuse_rs.wasm:0x43f0e
$_dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hffc6db5e0694434e @ caniuse_rs.wasm:0x43b46
__wbg_adapter_26 @ caniuse_rs.js:257
real @ caniuse_rs.js:243
```
Further if I enter more I get more errors:
```rust
caniuse_rs.js:458 panicked at 'called `Option::unwrap()` on a `None` value', src/components/app.rs:95:88

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (https://caniuse.rs/caniuse_rs.js:446:23)
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[760]:0x547e2
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[310]:0x39f61
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[604]:0x42e6b
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[564]:0x42245
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[387]:0x3dcbe
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[363]:0x3cda0
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[104]:0x1937f
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[715]:0x43f0e
    at https://caniuse.rs/caniuse_rs.wasm:wasm-function[678]:0x43b46


imports.wbg.__wbg_error_09919627ac0992f5 @ caniuse_rs.js:458
$func760 @ caniuse_rs.wasm:0x54867
$func310 @ caniuse_rs.wasm:0x39f61
$func604 @ caniuse_rs.wasm:0x42e6b
$func564 @ caniuse_rs.wasm:0x42245
$func387 @ caniuse_rs.wasm:0x3dcbe
$func363 @ caniuse_rs.wasm:0x3cda0
$func104 @ caniuse_rs.wasm:0x1937f
$func715 @ caniuse_rs.wasm:0x43f0e
$_dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hffc6db5e0694434e @ caniuse_rs.wasm:0x43b46
__wbg_adapter_26 @ caniuse_rs.js:257
real @ caniuse_rs.js:243
caniuse_rs.wasm:0x39f82 Uncaught RuntimeError: unreachable
    at caniuse_rs.wasm:0x39f82
    at caniuse_rs.wasm:0x42e6b
    at caniuse_rs.wasm:0x42245
    at caniuse_rs.wasm:0x3dcbe
    at caniuse_rs.wasm:0x3cda0
    at caniuse_rs.wasm:0x1937f
    at caniuse_rs.wasm:0x43f0e
    at caniuse_rs.wasm:0x43b46
    at __wbg_adapter_26 (caniuse_rs.js:257:14)
    at HTMLBodyElement.real (caniuse_rs.js:243:24)
$func310 @ caniuse_rs.wasm:0x39f82
$func604 @ caniuse_rs.wasm:0x42e6b
$func564 @ caniuse_rs.wasm:0x42245
$func387 @ caniuse_rs.wasm:0x3dcbe
$func363 @ caniuse_rs.wasm:0x3cda0
$func104 @ caniuse_rs.wasm:0x1937f
$func715 @ caniuse_rs.wasm:0x43f0e
$_dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hffc6db5e0694434e @ caniuse_rs.wasm:0x43b46
__wbg_adapter_26 @ caniuse_rs.js:257
real @ caniuse_rs.js:243
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
Unchecked runtime.lastError: The message port closed before a response was received.
```
It also makes me unable to click any links anymore.

Similar thing on firefox:
```rust
panicked at 'No current Scope. `use_context` can only be called inside function components', /home/jplatte/.cargo/registry/src/github.com-1ecc6299db9ec823/yew-0.19.3/src/functional/hooks/use_context.rs:38:10

Stack:

init/imports.wbg.__wbg_new_693216e109162396@https://caniuse.rs/caniuse_rs.js:446:23
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[760]:0x547e2
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[310]:0x39f61
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[604]:0x42e91
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[718]:0x43feb
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[98]:0x16538
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[204]:0x2d94c
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[93]:0x13d8e
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[277]:0x37f2e
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[387]:0x3dca6
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[363]:0x3cda0
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[104]:0x1937f
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[715]:0x43f0e
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[678]:0x43b46
__wbg_adapter_26@https://caniuse.rs/caniuse_rs.js:257:14
real@https://caniuse.rs/caniuse_rs.js:243:24
EventListener.handleEvent*init/imports.wbg.__wbg_addEventListener_55682f77717d7665/<@https://caniuse.rs/caniuse_rs.js:531:29
handleError@https://caniuse.rs/caniuse_rs.js:286:22
init/imports.wbg.__wbg_addEventListener_55682f77717d7665@https://caniuse.rs/caniuse_rs.js:530:83
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[610]:0x42fda
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[101]:0x176a1
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[95]:0x1525e
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[87]:0xf6bf
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[185]:0x2ad67
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[82]:0x6edb
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[87]:0xf7a6
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[185]:0x2ad67
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[82]:0x6edb
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[87]:0xf7a6
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[185]:0x2ad67
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[82]:0x6edb
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[87]:0xf7a6
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[79]:0x3423
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[93]:0x13d8e
@https://caniuse.rs/caniuse_rs.wasm:wasm-function[107]:0x1a196
run@https://caniuse.rs/caniuse_rs.js:263:14
main@https://caniuse.rs/caniuse_rs.js:712:13
async*@https://caniuse.rs/caniuse_rs.js:714:9
@https://caniuse.rs/caniuse_rs.js:722:3


caniuse_rs.js:458:25
    __wbg_error_09919627ac0992f5 https://caniuse.rs/caniuse_rs.js:458
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:346215
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:237409
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:274065
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:278507
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:91448
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:186700
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:81294
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:229166
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:253094
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:249248
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:103295
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:278286
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:277318
    __wbg_adapter_26 https://caniuse.rs/caniuse_rs.js:257
    real https://caniuse.rs/caniuse_rs.js:243
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_55682f77717d7665 https://caniuse.rs/caniuse_rs.js:531
    handleError https://caniuse.rs/caniuse_rs.js:286
    __wbg_addEventListener_55682f77717d7665 https://caniuse.rs/caniuse_rs.js:530
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:274394
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:95905
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:86622
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:63167
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:175463
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:28379
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:63398
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:175463
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:28379
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:63398
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:175463
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:28379
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:63398
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:13347
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:81294
    <anonymous> https://caniuse.rs/caniuse_rs.wasm:106902
    run https://caniuse.rs/caniuse_rs.js:263
    main https://caniuse.rs/caniuse_rs.js:712
    <anonymous> https://caniuse.rs/caniuse_rs.js:714
    <anonymous> https://caniuse.rs/caniuse_rs.js:722
```

System specs:
```
Windows 10
Google Chrome - Version 98.0.4758.102 (Official Build) (64-bit)
Firefox - 97.0.1 (64-bit)
```

**Comment by jplatte** [comment]
Can reproduce. Probably an issue with the recent Yew upgrade. I'll revert that and/or try to figure out what's wrong soon.

**Comment by jplatte** [comment]
Reverted the change for now. Seems like the older Yew version results in *much* bigger `wasm` bundle size, but hopefully I can just redo the upgrade soon.
